### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by gustavo2321719** [ImSejin/kakao-webtoon-downloader#2]
I have tried everything but I can't get it to work, please help.

**Comment by ImSejin** [comment]
There's something I need to know before I explain.
Do you know the usage of `node.js` and `npm`?

**Comment by gustavo2321719** [comment]
I know the basics

**Comment by gustavo2321719** [comment]
the truth is that I don't know how to use npm or node.js, if it wouldn't be too much trouble, I would like some reference images to know what exactly I should do.

**Comment by ImSejin** [comment]
1. Install node.js at [here](https://nodejs.org/).
2. Download all the source files of this repository.
3. Open cli at where the sources are.
4. Run command `npm install`.
5. See readme.

**Comment by gustavo2321719** [comment]
thank you very much for your help, I just needed to install npm

**Comment by ImSejin** [comment]
Can I close thie issue?
